/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as ShellWorkRouteImport } from './routes/_shell.work'
import { Route as ShellTerminalsRouteImport } from './routes/_shell.terminals'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellHomeRouteImport } from './routes/_shell.home'
import { Route as ShellSessionsSessionIdRouteImport } from './routes/_shell.sessions.$sessionId'
import { Route as ShellProjectsProjectIdRouteImport } from './routes/_shell.projects.$projectId'
import { Route as ShellHomeOpenLoopsRouteImport } from './routes/_shell.home_.open-loops'
import { Route as ShellHomeMemoryRouteImport } from './routes/_shell.home_.memory'
import { Route as ShellHomeHistoryRouteImport } from './routes/_shell.home_.history'
import { Route as ShellHomeDailyCloseRouteImport } from './routes/_shell.home_.daily-close'
import { Route as ShellHomeChatRouteImport } from './routes/_shell.home_.chat'
import { Route as ShellProjectsProjectIdSettingsRouteImport } from './routes/_shell.projects.$projectId_.settings'
import { Route as ShellProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_shell.projects.$projectId_.sessions.$sessionId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWorkRoute = ShellWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTerminalsRoute = ShellTerminalsRouteImport.update({
  id: '/terminals',
  path: '/terminals',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeRoute = ShellHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSessionsSessionIdRoute = ShellSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdRoute = ShellProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeOpenLoopsRoute = ShellHomeOpenLoopsRouteImport.update({
  id: '/home_/open-loops',
  path: '/home/open-loops',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeMemoryRoute = ShellHomeMemoryRouteImport.update({
  id: '/home_/memory',
  path: '/home/memory',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeHistoryRoute = ShellHomeHistoryRouteImport.update({
  id: '/home_/history',
  path: '/home/history',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeDailyCloseRoute = ShellHomeDailyCloseRouteImport.update({
  id: '/home_/daily-close',
  path: '/home/daily-close',
  getParentRoute: () => ShellRoute,
} as any)
const ShellHomeChatRoute = ShellHomeChatRouteImport.update({
  id: '/home_/chat',
  path: '/home/chat',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsProjectIdSettingsRoute =
  ShellProjectsProjectIdSettingsRouteImport.update({
    id: '/projects/$projectId_/settings',
    path: '/projects/$projectId/settings',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellProjectsProjectIdSessionsSessionIdRoute =
  ShellProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId_/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/home': typeof ShellHomeRoute
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/work': typeof ShellWorkRoute
  '/home/chat': typeof ShellHomeChatRoute
  '/home/daily-close': typeof ShellHomeDailyCloseRoute
  '/home/history': typeof ShellHomeHistoryRoute
  '/home/memory': typeof ShellHomeMemoryRoute
  '/home/open-loops': typeof ShellHomeOpenLoopsRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/home': typeof ShellHomeRoute
  '/settings': typeof ShellSettingsRoute
  '/terminals': typeof ShellTerminalsRoute
  '/work': typeof ShellWorkRoute
  '/': typeof ShellIndexRoute
  '/home/chat': typeof ShellHomeChatRoute
  '/home/daily-close': typeof ShellHomeDailyCloseRoute
  '/home/history': typeof ShellHomeHistoryRoute
  '/home/memory': typeof ShellHomeMemoryRoute
  '/home/open-loops': typeof ShellHomeOpenLoopsRoute
  '/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/projects/$projectId/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/projects/$projectId/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/home': typeof ShellHomeRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/terminals': typeof ShellTerminalsRoute
  '/_shell/work': typeof ShellWorkRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/home_/chat': typeof ShellHomeChatRoute
  '/_shell/home_/daily-close': typeof ShellHomeDailyCloseRoute
  '/_shell/home_/history': typeof ShellHomeHistoryRoute
  '/_shell/home_/memory': typeof ShellHomeMemoryRoute
  '/_shell/home_/open-loops': typeof ShellHomeOpenLoopsRoute
  '/_shell/projects/$projectId': typeof ShellProjectsProjectIdRoute
  '/_shell/sessions/$sessionId': typeof ShellSessionsSessionIdRoute
  '/_shell/projects/$projectId_/settings': typeof ShellProjectsProjectIdSettingsRoute
  '/_shell/projects/$projectId_/sessions/$sessionId': typeof ShellProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/settings'
    | '/terminals'
    | '/work'
    | '/home/chat'
    | '/home/daily-close'
    | '/home/history'
    | '/home/memory'
    | '/home/open-loops'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/settings'
    | '/terminals'
    | '/work'
    | '/'
    | '/home/chat'
    | '/home/daily-close'
    | '/home/history'
    | '/home/memory'
    | '/home/open-loops'
    | '/projects/$projectId'
    | '/sessions/$sessionId'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/sessions/$sessionId'
  id:
    | '__root__'
    | '/_shell'
    | '/_shell/home'
    | '/_shell/settings'
    | '/_shell/terminals'
    | '/_shell/work'
    | '/_shell/'
    | '/_shell/home_/chat'
    | '/_shell/home_/daily-close'
    | '/_shell/home_/history'
    | '/_shell/home_/memory'
    | '/_shell/home_/open-loops'
    | '/_shell/projects/$projectId'
    | '/_shell/sessions/$sessionId'
    | '/_shell/projects/$projectId_/settings'
    | '/_shell/projects/$projectId_/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/work': {
      id: '/_shell/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof ShellWorkRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/terminals': {
      id: '/_shell/terminals'
      path: '/terminals'
      fullPath: '/terminals'
      preLoaderRoute: typeof ShellTerminalsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home': {
      id: '/_shell/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ShellHomeRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sessions/$sessionId': {
      id: '/_shell/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof ShellSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId': {
      id: '/_shell/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ShellProjectsProjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home_/open-loops': {
      id: '/_shell/home_/open-loops'
      path: '/home/open-loops'
      fullPath: '/home/open-loops'
      preLoaderRoute: typeof ShellHomeOpenLoopsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home_/memory': {
      id: '/_shell/home_/memory'
      path: '/home/memory'
      fullPath: '/home/memory'
      preLoaderRoute: typeof ShellHomeMemoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home_/history': {
      id: '/_shell/home_/history'
      path: '/home/history'
      fullPath: '/home/history'
      preLoaderRoute: typeof ShellHomeHistoryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home_/daily-close': {
      id: '/_shell/home_/daily-close'
      path: '/home/daily-close'
      fullPath: '/home/daily-close'
      preLoaderRoute: typeof ShellHomeDailyCloseRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/home_/chat': {
      id: '/_shell/home_/chat'
      path: '/home/chat'
      fullPath: '/home/chat'
      preLoaderRoute: typeof ShellHomeChatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/settings': {
      id: '/_shell/projects/$projectId_/settings'
      path: '/projects/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ShellProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects/$projectId_/sessions/$sessionId': {
      id: '/_shell/projects/$projectId_/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof ShellProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellHomeRoute: typeof ShellHomeRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTerminalsRoute: typeof ShellTerminalsRoute
  ShellWorkRoute: typeof ShellWorkRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellHomeChatRoute: typeof ShellHomeChatRoute
  ShellHomeDailyCloseRoute: typeof ShellHomeDailyCloseRoute
  ShellHomeHistoryRoute: typeof ShellHomeHistoryRoute
  ShellHomeMemoryRoute: typeof ShellHomeMemoryRoute
  ShellHomeOpenLoopsRoute: typeof ShellHomeOpenLoopsRoute
  ShellProjectsProjectIdRoute: typeof ShellProjectsProjectIdRoute
  ShellSessionsSessionIdRoute: typeof ShellSessionsSessionIdRoute
  ShellProjectsProjectIdSettingsRoute: typeof ShellProjectsProjectIdSettingsRoute
  ShellProjectsProjectIdSessionsSessionIdRoute: typeof ShellProjectsProjectIdSessionsSessionIdRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellHomeRoute: ShellHomeRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTerminalsRoute: ShellTerminalsRoute,
  ShellWorkRoute: ShellWorkRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellHomeChatRoute: ShellHomeChatRoute,
  ShellHomeDailyCloseRoute: ShellHomeDailyCloseRoute,
  ShellHomeHistoryRoute: ShellHomeHistoryRoute,
  ShellHomeMemoryRoute: ShellHomeMemoryRoute,
  ShellHomeOpenLoopsRoute: ShellHomeOpenLoopsRoute,
  ShellProjectsProjectIdRoute: ShellProjectsProjectIdRoute,
  ShellSessionsSessionIdRoute: ShellSessionsSessionIdRoute,
  ShellProjectsProjectIdSettingsRoute: ShellProjectsProjectIdSettingsRoute,
  ShellProjectsProjectIdSessionsSessionIdRoute:
    ShellProjectsProjectIdSessionsSessionIdRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
