import type { WebContents } from "electron";
import { afterEach, describe, expect, it, vi } from "vitest";
import { createWaldoBridgeHandlers, type WaldoBridgeDeps } from "./waldo-bridge-handler";
const code = "A".repeat(43);
const token = "B".repeat(43);
const input = { code, label: "Mac", capabilities: ["machine_state_query", "notify_local"] };
function harness(status = 204) { const frame = {} as never; const shell = { isDestroyed: vi.fn(() => false), mainFrame: frame } as unknown as WebContents; const response = { status, ok: status >= 200 && status < 300, json: vi.fn(async () => ({ state: "online", ready: true, device_id: "dev", label: "Mac", token: "must-not-return", owner_id: "owner" })) }; const deps: WaldoBridgeDeps = { getShellWebContents: vi.fn(() => shell), getDaemonConnection: vi.fn(() => ({ port: 3031 })), bridgeLocalToken: () => token, fetch: vi.fn(async () => response) as never }; return { deps, shell, response, event: { sender: shell, senderFrame: frame }, handlers: createWaldoBridgeHandlers(deps) }; }
afterEach(() => vi.restoreAllMocks());
describe("waldo bridge private IPC", () => {
 it("rejects a sender that is not the live primary shell main frame", async () => { for (const kind of ["sender", "subframe", "absent", "destroyed"]) { const h = harness(); const event = { ...h.event }; if (kind === "sender") event.sender = {} as never; if (kind === "subframe") event.senderFrame = {} as never; if (kind === "absent") vi.mocked(h.deps.getShellWebContents).mockReturnValue(null); if (kind === "destroyed") vi.mocked(h.shell.isDestroyed).mockReturnValue(true); expect(await h.handlers.pair(event, input)).toStrictEqual({ ok: false, reason: "failed" }); expect(await h.handlers.status(event)).toStrictEqual({ ok: false, reason: "failed" }); expect(h.deps.fetch).not.toHaveBeenCalled(); } });
 it("sends exactly the documented body, URL and Authorization header without Origin", async () => { const h = harness(); expect(await h.handlers.pair(h.event, input)).toStrictEqual({ ok: true }); expect(h.deps.fetch).toHaveBeenCalledExactlyOnceWith("http://127.0.0.1:3031/internal/bridge/pair", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `KennelBridge ${token}` }, body: JSON.stringify(input) }); expect(h.response.json).not.toHaveBeenCalled(); });
 it.each([[204, undefined], [409, "recovery_required"], [404, "unavailable"], [503, "unavailable"], [400, "failed"], [401, "failed"], [403, "failed"], [500, "failed"]] as const)("maps HTTP %i to a small result without response bodies", async (status, reason) => { const h = harness(status); expect(await h.handlers.pair(h.event, input)).toStrictEqual(reason ? { ok: false, reason } : { ok: true }); expect(h.response.json).not.toHaveBeenCalled(); });
 it("maps network errors without returning or logging messages, code or credentials", async () => { const log = vi.spyOn(console, "log").mockImplementation(() => {}); const warn = vi.spyOn(console, "warn").mockImplementation(() => {}); const error = vi.spyOn(console, "error").mockImplementation(() => {}); const h = harness(); vi.mocked(h.deps.fetch).mockRejectedValue(new Error(code + token)); expect(await h.handlers.pair(h.event, input)).toStrictEqual({ ok: false, reason: "unavailable" }); expect(await h.handlers.status(h.event)).toStrictEqual({ ok: false, reason: "unavailable" }); expect([log.mock.calls, warn.mock.calls, error.mock.calls]).toStrictEqual([[], [], []]); });
 it("returns only allowlisted status fields", async () => { const h = harness(200); expect(await h.handlers.status(h.event)).toStrictEqual({ ok: true, state: "online", ready: true, deviceId: "dev", label: "Mac" }); expect(h.deps.fetch).toHaveBeenCalledExactlyOnceWith("http://127.0.0.1:3031/internal/bridge/status", { method: "GET", headers: { Authorization: `KennelBridge ${token}` } }); });
 it.each([404, 503, 400, 401, 403, 500])("maps status failure %i without reading a body", async status => { const h = harness(status); expect(await h.handlers.status(h.event)).toStrictEqual({ ok: false, reason: status === 404 || status === 503 ? "unavailable" : "failed" }); expect(h.response.json).not.toHaveBeenCalled(); });
 it("rejects malformed status and unavailable daemon safely", async () => { const h = harness(200); vi.mocked(h.response.json).mockResolvedValue({ state: "evil", ready: true } as never); expect(await h.handlers.status(h.event)).toStrictEqual({ ok: false, reason: "failed" }); vi.mocked(h.deps.getDaemonConnection).mockReturnValue(null); expect(await h.handlers.pair(h.event, input)).toStrictEqual({ ok: false, reason: "unavailable" }); });
 it.each([null, {}, { ...input, extra: true }, { ...input, code: "short" }, { ...input, code: "A".repeat(42) + "B" }, { ...input, label: "" }, { ...input, label: "é".repeat(61) }, { ...input, label: "\ud800" }, { ...input, label: "\udc00" }, { ...input, capabilities: [] }, { ...input, capabilities: ["notify_local", "machine_state_query"] }, { ...input, capabilities: ["approve"] }])("rejects invalid code, label or capabilities without fetch", async bad => { const h = harness(); expect(await h.handlers.pair(h.event, bad)).toStrictEqual({ ok: false, reason: "failed" }); expect(h.deps.fetch).not.toHaveBeenCalled(); });
 it.each(["notify_local", "machine_state_query"])("accepts a valid single capability", async capability => { const h = harness(); expect(await h.handlers.pair(h.event, { ...input, capabilities: [capability] })).toStrictEqual({ ok: true }); });
});
